INSERT INTO FIFTEENGG.POSITIONTYPE (POSITION, POSITIONNAME) VALUES (1, '탑');
INSERT INTO FIFTEENGG.POSITIONTYPE (POSITION, POSITIONNAME) VALUES (2, '미드');
INSERT INTO FIFTEENGG.POSITIONTYPE (POSITION, POSITIONNAME) VALUES (3, '정글');
INSERT INTO FIFTEENGG.POSITIONTYPE (POSITION, POSITIONNAME) VALUES (4, '원딜');
INSERT INTO FIFTEENGG.POSITIONTYPE (POSITION, POSITIONNAME) VALUES (5, '서포터');
INSERT INTO FIFTEENGG.POSITIONTYPE (POSITION, POSITIONNAME) VALUES (6, '자유');